exe:
	make -C libgtest-report flo
	make -C gtest-report-print exe

all:
	make -C libgtest-report all
	make -C gtest-report-print all

dll:
	make -C libgtest-report dll

flo:
	make -C libgtest-report flo
	make -C gtest-report-print flo

clean:
	make -C libgtest-report clean
	make -C gtest-report-print clean
